# Generated by Django 5.2.5 on 2025-08-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1_personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
