# Generated by Django 5.2.5 on 2025-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_4_seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmantenimientomodel',
            name='fecha_programada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='custodiamodel',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
