# Generated by Django 5.2.5 on 2025-09-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_4_seguimientos', '0002_alter_controlmantenimientomodel_fecha_programada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodiamodel',
            name='fecha_programada',
            field=models.DateField(),
        ),
    ]
