# Generated by Django 5.2.5 on 2025-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2_suministros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomodel',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
