# Generated by Django 5.2.5 on 2025-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2_suministros', '0002_alter_serviciomodel_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
