# Generated by Django 5.2.5 on 2025-09-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2_suministros', '0003_alter_productomodel_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
