# Generated by Django 5.2.5 on 2025-09-10 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2_suministros', '0004_productomodel_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomodel',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app_2_suministros.productomodel')),
            ],
        ),
    ]
