# Generated by Django 5.2.5 on 2025-09-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2_suministros', '0005_remove_productomodel_imagen_imagenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmodel',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
