# Generated by Django 5.2.5 on 2025-09-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2_suministros', '0006_alter_imagenmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmodel',
            name='imagen',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
